id: P004333
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 11:11:52.078397
source_metadata:
  id: bdr:W1KG18579
  title: གནམ་བདེ་སྒོ་མོའི་སྙན་ཚིག་འདྲ་བཤུས།
  author: ''
  volumes:
    bfe1c9b7e2d740e69c4338001a7a35e9:
      image_group_id: I1KG18729
      title: ''
      volume_number: 1
      total_pages: 554
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
