id: IEEB3E797
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:04:21+00:00'
last_modified: '2022-06-07T22:04:07.464182+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG18579
  title: གནམ་བདེ་སྒོ་མོའི་སྙན་ཚིག་འདྲ་བཤུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3842':
      image_group_id: I1KG18729
      title: ''
      total_pages: 554
      order: 1
      base_file: 3842.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
